name: CI
on: [pull_request, push]

jobs:
  build-linux:
#    name: Build (Linux)
    strategy:
      matrix:
        os: [ubuntu-24.04]
#        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{matrix.os}}
    steps:
      - name: lsla 1
# /home/runner/work/avidemux2/avidemux2
        run: pwd && ls -la .. && ls -la
      - name: Source checkout
        uses: actions/checkout@v4 
        with:
          submodules: recursive
# will need to clone avidemux2_i18n, instead.
          repository: mean00/avidemux2
          ref: 34667ad7467e34f25e5707f01813b36c29063189
      - name: lsla 2
        run: pwd && ls -la .. && ls -la
      - name: Install build dependencies
        run: bash createDebFromSourceUbuntu.bash --deps-only
      - name: lsla deps
        run: ls -la /usr/lib/x86_64-linux-gnu/libvpx*
      - name: lsla 3
        run: pwd && ls -la .. && ls -la
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            build*
            install
          key: build-${{github.sha}}
          restore-keys: |
            build-
      - name: Build
# --enable-qt5 : downgrade from default qt6.
# --rebuild
        run: bash bootStrap.bash
           # --with-system-libass
# New, "in-tree": buildCli, buildCore, buildPluginsCLI, buildPluginsCommon, buildPluginsQt6, buildPluginsSettings, buildQt6, install.
      - name: lsla 4
        run: pwd && ls -la .. && ls -la && ls -laR install/

# Ajouter un cache, voire l'option rebuild !?
