# .github/workflows/ci.yml

name: CI
on: [pull_request, push]

jobs:
  build-linux:
#    name: Build (Linux)
    strategy:
      matrix:
        os: [ubuntu-24.04]
#        os: [ubuntu-22.04, ubuntu-24.04]
#      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - name: lsla 1
# /home/runner/work/avidemux2/avidemux2
        run: pwd && ls -la .. && ls -la
      - name: Source checkout
        uses: actions/checkout@v4 
        with:
          submodules: recursive
# will need to clone avidemux2_i18n, instead.
          repository: mean00/avidemux2
          ref: master
      - name: lsla 2
        run: pwd && ls -la .. && ls -la
      - name: Install build dependencies
        run: bash createDebFromSourceUbuntu.bash --deps-only
      - name: lsla deps
        run: ls -la /usr/lib/x86_64-linux-gnu/libvpx*
      - name: lsla 3
        run: pwd && ls -la .. && ls -la
# cache + --rebuild: "8" min -> 4.5" min :-)
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            build*
            install
          key: build-${{matrix.os}}-qt6-${{github.sha}}
          restore-keys: |
            build-${{matrix.os}}-qt6-
      - name: lsla 3 after cache
        run: pwd && ls -la .. && ls -la
      - name: Build
# --enable-qt5 : downgrade from default qt6.
# --rebuild
# 22.04 (qt4) and 24.04 (qt4):
#    buildQt4:Cmake started...
# ** Failed at cmake,result in /tmp/logCmakebuildQt4 **
# 22.04 (qt5) and 24.04 (qt5):
#     buildQt5:Cmake started...
# ** Failed at cmake,result in /tmp/logCmakebuildQt5 **
# 22.04 (qt6):
#    buildQt6:Build started...
# ** Failed at make -j 4, result in /tmp/logbuildQt6 **
        run: bash bootStrap.bash --rebuild
           # --with-system-libass
# New, "in-tree": buildCli, buildCore, buildPluginsCLI, buildPluginsCommon, buildPluginsQt6, buildPluginsSettings, buildQt6, install.
      - name: lsla 4
        run: pwd && ls -la .. && ls -la && ls -laR install/
# On Trisquel 11.0.1:
# $ ./run_avidemux_template_qt6.sh
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: error while loading shared libraries: libQt6OpenGLWidgets.so.6: cannot open shared object file: No such file or directory
# Fichier absent:
# $ find /usr/lib* -iname "libQt6O*"
# /usr/lib/x86_64-linux-gnu/libQt6OpenGL.so.6.2.4
# /usr/lib/x86_64-linux-gnu/libQt6OpenGL.so.6
      - name: Upload compiled binaries
        uses: actions/upload-artifact@v4
        with:
          # compression-level: 9 # 15326537 -> 15292214, -0,2% :-(
          name: avidemux2-install-${{matrix.os}}-qt6-${{github.sha}}
# To try, after it runs:            !install/usr/share/
          path: |
            install/
            !install/usr/include/
            install/usr/include/avidemux/*.*/ADM_coreConfig.h
      - name: Create an (qt6) appImage for Debian 12/BW and Ubuntu 22.04/JJ
#         if: false
# --rebuild
# 24.04 (qt6):
# cp: cannot stat '/usr/lib/x86_64-linux-gnu/libvpx.so.7': No such file or directory
# 24.04 has libvpx.so.9, not expected libvpx.so.7.
        run: |
          chmod u+x ./makeAppImageBookwormMinimal.sh
          ./makeAppImageBookwormMinimal.sh
      - name: lsla 5
        run: pwd && ls -la .. && ls -la && ls -laR install/
      - name: Upload appImage
        if: false
        uses: actions/upload-artifact@v4
        with:
          name: avidemux2-${{matrix.os}}-qt6-${{github.sha}}.appImage
          path: |
            build/bootcd.iso
            build/livecd.iso

# Ajouter un cache (voire ccache !?), voire l'option rebuild !?
