# .github/workflows/ci.yml

name: CI
on: [pull_request, push]

jobs:
  build-linux:
#    name: Build (Linux)
    strategy:
      matrix:
#        os: [ubuntu-22.04]
        os: [ubuntu-22.04, ubuntu-24.04]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - name: lsla 1
# /home/runner/work/avidemux2/avidemux2
        run: pwd && ls -la .. && ls -la
      - name: Source checkout
        uses: actions/checkout@v4 
        with:
          submodules: recursive
# will need to clone avidemux2_i18n, instead.
#          repository: mean00/avidemux2
#          ref: master
      - name: lsla 2
        run: pwd && ls -la .. && ls -la
      - name: Install build dependencies
        run: bash createDebFromSourceUbuntu.bash --deps-only
      - name: lsla deps
#        run: ls -laR /usr/ | grep qt6
        run: ls -la /usr/lib/x86_64-linux-gnu/libx264.so*
      - name: lsla 3
        run: pwd && ls -la .. && ls -la
# cache + --rebuild: "8" min -> 4.5" min :-)
      - name: Set up cache
        if: false # To re-enable _after_ build is fixed. # But appImage overwrites(!?) install, not good for caching !!? (split into 2 caches, and/or only run 1 of them !!?)
        uses: actions/cache@v4
        with:
          path: |
            build*
            install
          key: build-${{matrix.os}}-qt6-${{github.sha}}
          restore-keys: |
            build-${{matrix.os}}-qt6-
      - name: lsla 3 after cache
        run: pwd && ls -la .. && ls -la
      - name: Build
# --enable-qt5 : downgrade from default qt6.
# --rebuild
# 22.04 (qt4) and 24.04 (qt4):
#    buildQt4:Cmake started...
# ** Failed at cmake,result in /tmp/logCmakebuildQt4 **
# 22.04 (qt5) and 24.04 (qt5):
#     buildQt5:Cmake started...
# ** Failed at cmake,result in /tmp/logCmakebuildQt5 **
# 22.04 (qt6):
#    buildQt6:Build started...
# ** Failed at make -j 4, result in /tmp/logbuildQt6 **
# cat:
# lrelease: could not find a Qt installation of 'qt6'
# make[2]: *** [i18n/CMakeFiles/qmfiles.dir/build.make:122: i18n/avidemux_ca.qm] Error 1
# make[2]: Leaving directory '/home/runner/work/avidemux2/avidemux2/buildQt6'
# make[1]: *** [CMakeFiles/Makefile2:1672: i18n/CMakeFiles/qmfiles.dir/all] Error 2
# +
# make[1]: Leaving directory '/home/runner/work/avidemux2/avidemux2/buildQt6'
# make: *** [Makefile:139: all] Error 2
        run: bash bootStrap.bash
# New, "in-tree": buildCli, buildCore, buildPluginsCLI, buildPluginsCommon, buildPluginsQt6, buildPluginsSettings, buildQt6, install.
      - name: lsla 4
        run: pwd && ls -la .. && ls -la && ls -laR install/
# (22.04 and 24.04) on Trisquel 11.0.1:
# $ ./run_avidemux_template_qt6.sh
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: error while loading shared libraries: libQt6OpenGLWidgets.so.6: cannot open shared object file: No such file or directory
# Fichier absent:
# $ find /usr/lib* -iname "libQt6O*"
# /usr/lib/x86_64-linux-gnu/libQt6OpenGL.so.6.2.4
# /usr/lib/x86_64-linux-gnu/libQt6OpenGL.so.6
# $ sudo apt install libqt6openglwidgets6
# Then (22.04 build starts on Trisquel !! Does it actually work?)
# It "misses" (my build or by design?):
# Audio: Faad2 decoder
# Video Decoder: AV1 ['AV1 (libaom)' added to Video Encoder...]
# Audio Encoders: FDK AAC encoder, Faac AAC encoder [These are present in appImage (only).]
# Muxers: MP4V2 muxer
# Then (24.04 build can't run on Trisquel 11 (U 22.04) [GLIBC 2.35, QT 6.2 !??, ...] !!)
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/tqme/Downloads/avidemux2-dev/install/usr/bin/avidemux3_qt6)
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /home/tqme/Downloads/avidemux2-dev/install/usr/bin/avidemux3_qt6)
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: /lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.4' not found (required by /home/tqme/Downloads/avidemux2-dev/install/usr/bin/avidemux3_qt6)
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by /home/tqme/Downloads/avidemux2-dev/install/usr/lib/x86_64-linux-gnu/libADM_coreUtils6.so)
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: /lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.4' not found (required by /home/tqme/Downloads/avidemux2-dev/install/usr/lib/x86_64-linux-gnu/libADM_UIQT66.so)
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /home/tqme/Downloads/avidemux2-dev/install/usr/lib/x86_64-linux-gnu/libADM_coreScript.so)
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: /lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.4' not found (required by /home/tqme/Downloads/avidemux2-dev/install/usr/lib/x86_64-linux-gnu/libADM_render6_QT6.so)
# .../avidemux2-dev/install/usr/bin/avidemux3_qt6: /lib/x86_64-linux-gnu/libQt6Core.so.6: version `Qt_6.4' not found (required by /home/tqme/Downloads/avidemux2-dev/install/usr/lib/x86_64-linux-gnu/libADM_openGLQT66.so)
# $ sudo apt remove libqt6openglwidgets6
      - name: Upload compiled binaries
        if: ${{ matrix.os == 'ubuntu-22.04' }} # 24.04 does not run on my (older) T 11.
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9 # Compression ratio: 6 = 2.55 :-) # 15326537 -> 15292214, -0,2% :-(
          name: avidemux2-install-${{matrix.os}}-qt6-${{github.sha}}
# To try, after it runs:            !install/usr/share/
          path: |
            install/
            !install/usr/include/
            install/usr/include/avidemux/*.*/ADM_coreConfig.h
      - name: Create an (qt6) appImage for Debian 12/BW and Ubuntu 22.04/JJ
        if: ${{ matrix.os == 'ubuntu-22.04' }} # Building on (newer) 24.04 is not supported (yet).
# --rebuild

# 22.04 (qt6):
#  ** Creating AppImage file **
# cp: cannot stat '/usr/lib/x86_64-linux-gnu/libx264.so.164': No such file or directory
# From appImage/deployBookwormMinimal.sh

# 24.04 has it.

# 22.04 has libx264.so.163, not expected libx264.so.164.
# On Trisquel 11.0.1:
# $ ll /usr/lib/x86_64-linux-gnu/libx264.so*
# -rw-r--r-- 1 root root 1863256 mars   7  2022 /usr/lib/x86_64-linux-gnu/libx264.so.163

# 24.04 (qt6):
#  ** Creating AppImage file **
# cp: cannot stat '/usr/lib/x86_64-linux-gnu/libvpx.so.7': No such file or directory
# From appImage/deployBookwormMinimal.sh

# 24.04 has libvpx.so.9, not expected libvpx.so.7.

# 22.04 has it.
# On Trisquel 11.0.1:
# $ ll -d /usr/lib/x86_64-linux-gnu/libvpx*
# lrwxrwxrwx 1 root root      15 juin   5  2024 /usr/lib/x86_64-linux-gnu/libvpx.so.7 -> libvpx.so.7.0.0
# lrwxrwxrwx 1 root root      15 juin   5  2024 /usr/lib/x86_64-linux-gnu/libvpx.so.7.0 -> libvpx.so.7.0.0
# -rw-r--r-- 1 root root 3176976 juin   5  2024 /usr/lib/x86_64-linux-gnu/libvpx.so.7.0.0

# $ ldd --version
# ldd (Ubuntu GLIBC 2.35-0ubuntu3.9+11.0trisquel1) 2.35
        run: |
          chmod u+x ./makeAppImageBookwormMinimal.sh
          ./makeAppImageBookwormMinimal.sh
      - name: lsla 5
        run: pwd && ls -la .. && ls -la && ls -laR install/
      - name: Upload appImage
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0 # Compression ratio: 6 = 1.01 :-(
          name: avidemux2-${{matrix.os}}-qt6-${{github.sha}}.appImage
          path: avidemuxLinux_GLIBC_2.36_amd64_??????_????.app

# Ajouter un cache (voire ccache !?), voire l'option rebuild !?
